### PR TITLE
Tag Prop feature

### PR DESCRIPTION
**Pull request by idangoldman**
Hey @Akirami , how are you doing?

Searched for a Vue markdown parser and your repo had the best (and working) solution for my use case.

Had one feature missing, a different output wrap tag than the default `div` tag
So, I have added it and hope you accept my pull request. 

Inside a Vue component:
```
<VueMarkdown tag="article">...Markdown content...</VueMarkdown>
```

Output:
```
<article>...Markdown content...</article>
```

Let me know it you need me to edit something in this pull request,
Have a nice one.

### CODE REVIEW

**Comment by Akirami** [comment]
Hi @idangoldman, i don't have time to test it, would you be interested in joining this repository ?

**Comment by idangoldman** [comment]
@Akirami sure, what kind of tests you want me to run?

**Comment by Akirami** [comment]
@dangoldman test your PR and if it's OK, you can merge it.

Thanks ;)

**Comment by idangoldman** [comment]
@Akirami done, now a version bump on NPM? 😅

**Comment by Akirami** [comment]
@idangoldman Thanks, do you have an account on NPM?

**Comment by idangoldman** [comment]
@Akirami, yes same handle as my Github account.

**Comment by Akirami** [comment]
@idangoldman Ypu have an invit.

**Comment by idangoldman** [comment]
@Akirami,
Ok then; I guess I'm doing a version release this week 😅

**Comment by idangoldman** [comment]
@Akirami ,

Ok then; I guess I'm doing a version release 😅

**Pull request merged**
